# Generated by Django 4.1.2 on 2022-10-28 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_topic_rename_updates_room_updated_room_host_message_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='descripton',
            new_name='description',
        ),
    ]
